#!/usr/bin/env python3

import requests

def runPageSpeed(site):
    url = "https://www.googleapis.com/pagespeedonline/v4/runPagespeed?url="+site+"&strategy=desktop&key=[your-key]"
    response = requests.get(url)
    data = response.json()
    score = (data['ruleGroups']['SPEED']['score'])
    print (site + "\n" + 'PageSpeed Score: ' + str(score))

def urlArray():
    url_array = []
    path = '/website-list.txt'
    pagespeed_file = open(path,'r')
    for line in pagespeed_file:
        line = line.rstrip('\n') 
        url_array.append(line)
    pagespeed_file.close()
    for url in url_array:
        runPageSpeed(url)

urlArray()
